### ISSUE TITLE
sequence tester resets configuration

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#183]
Running the sequence test tool with the testing targets seems to result in the cloud configuration being reset to the below  

This config sent to the device after starting the sequence test.

```
{"version":"1","pointset":{"points":{"superimposition_reading":{},"faulty_finding":{},"recalcitrant_angle":{}}},"system":{"min_loglevel":400},"timestamp":"2021-09-21T20:33:14.561Z"}
```

```
.2021-09-21T20:33:07Z starting test writeback_states
2021-09-21T20:33:07Z sending system_config
2021-09-21T20:33:07Z sending pointset_config
2021-09-21T20:33:07Z sending system_config
2021-09-21T20:33:07Z updated system loglevel 400
2021-09-21T20:33:07Z sending pointset_config
2021-09-21T20:33:07Z updated pointset config
2021-09-21T20:33:07Z start waiting for valid serial no
2021-09-21T20:33:09Z received update_state
2021-09-21T20:33:09Z update state
2021-09-21T20:33:09Z received system_states
2021-09-21T20:33:09Z updating system state
2021-09-21T20:33:09Z received state last_config Sun Sep 12 12:10:34 BST 2021
2021-09-21T20:33:09Z Received serial no N/A
2021-09-21T20:33:09Z finished waiting for valid serial no
2021-09-21T20:33:09Z start waiting for point not_exist to have value_state default (null)
2021-09-21T20:33:09Z received pointset_states
2021-09-21T20:33:09Z updating pointset state
2021-09-21T20:33:09Z received state pointset
2021-09-21T20:33:14Z received pointset_configs
2021-09-21T20:33:15Z received system_configs
2021-09-21T20:33:17Z received update_config
2021-09-21T20:33:17Z update config
2021-09-21T20:33:17Z received pointset_events
2021-09-21T20:33:17Z received update_state
2021-09-21T20:33:17Z update state
2021-09-21T20:33:17Z received system_states
2021-09-21T20:33:17Z updating system state
2021-09-21T20:33:17Z received state last_config Tue Sep 21 21:33:14 BST 2021
2021-09-21T20:33:17Z received pointset_states
2021-09-21T20:33:17Z updating pointset state
2021-09-21T20:33:17Z received state pointset
2021-09-21T20:33:18Z received update_config
2021-09-21T20:33:18Z update config
2021-09-21T20:33:19Z received pointset_events
2021-09-21T20:33:19Z received update_state
2021-09-21T20:33:19Z update state
2021-09-21T20:33:19Z received pointset_states
2021-09-21T20:33:19Z updating pointset state
2021-09-21T20:33:19Z received state pointset
2021-09-21T20:33:19Z received system_states
2021-09-21T20:33:19Z updating system state
2021-09-21T20:33:19Z received state last_config Tue Sep 21 21:33:14 BST 2021
2021-09-21T20:33:39Z received pointset_events
2021-09-21T20:33:39Z received update_state
2021-09-21T20:33:39Z update state
2021-09-21T20:33:39Z received system_states
2021-09-21T20:33:39Z updating system state
2021-09-21T20:33:39Z received state last_config Tue Sep 21 21:33:14 BST 2021
2021-09-21T20:33:39Z received pointset_states
2021-09-21T20:33:39Z updating pointset state
2021-09-21T20:33:39Z received state pointset
2021-09-21T20:34:07Z failed timeout waiting for point not_exist to have value_state default (null)
RESULT fail writeback_states timeout waiting for point not_exist to have value_state default (null)
```

**Comment by grafnu** [comment]
Ok, this should be fixed now, although not extensively tested!

The cloud configuration will be changed, yes -- but that's WAI.  The problem was that the point-names were not right. If there was some other behavior you were looking for then let me know.

commit d586a98a1da864e9560efba4bbcd83470f647d43 (HEAD -> master, faucet/master)
Author: Trevor <grafnu@users.noreply.github.com>
Date:   Tue Sep 21 20:58:15 2021 -0700

    Fix sequence testing writeback point design (#184)

**Comment by noursaidi** [comment]
It's fixed the point names - but I'm still having issues with testing with a proxied device on a gateway as the references and localnet fields that are needed for operation are removed.  I'd have expected the existing configuration to be updated rather than regenerated, and ideally the previous configuration to be reinstated once the test is done

Configuration from sequence test:
```
{"version":"1","pointset":{"points":{"actuator_feedback":{},"actuator_control":{}}},"system":{"min_loglevel":400},"timestamp":"2021-09-22T08:24:06.732Z"}
```

Expected configuration (output from registrar tool)
```
"localnet": {
    "subsystem": {
      "bacnet": {
        "local_id": "4148893" // needed
      }
    }
  },
  "gateway": {
    "gateway_id": "GAT-100"
  },
  "pointset": {
    "points": {
      "actuator_control":{
        "ref": "AO1105.Present_Value", // Needed
        "units": "Percent"
      },
      "actuator_feedback":{
        "ref": "AI1106.Present_Value", // Needed 
        "units": "Percent"
      }
    }
  },
```

**Comment by grafnu** [comment]
Ok, now I believe I have fixed this. Please give the latest version a try!  I didn't get a chance to extensively test it, but it does base the configuraiton off of the generated one which should have all the intermediate information -- and then it restores it at the end for good measure.

**Comment by noursaidi** [comment]
Almost there in my testing. The link below has my console output and the config blocks (from IoT Core Console on the device page). I've tried to tie up the sequence of the config block, but this result shows:
- The `localnet` block is still lost completely
- The `ref` key is lost from the points at the end of the test, and during the `writeback_states` test 
- The `ref` key returned for the second and third tests, but lost at the end of the test
- The config is updated several times at the end of the test

https://docs.google.com/document/d/1DQMvtHwn6TLl4WAll7uELPrid6eO3mrg-VjWfJTUwMo/edit?usp=sharing

**Comment by grafnu** [comment]
What I'd like to do is take a look at the cloud-side logs for the function,
it will have better logging facilities for this.  What GCP project is this,
and which device, exactly?  (And do I have access?)

Also, is the site_model for this available in some git repo somewhere?  (I
got a new system at one point so I might have lost it)

I'll try to reproduce on my end as well with a test setup...

**Comment by noursaidi** [comment]
You should have access to the below:
Site model: https://github.com/noursaidi/nes-site-model 
GCP Link: https://console.cloud.google.com/project=daq1-273309 

The device was "ACT-1" or "SNS-1" (both proxy devices)

**Comment by grafnu** [comment]
Ok -- let's just try and fix "the end of the test" first, and then we can
address others. Note that the "updated several times at the end of the
test" itself shouldn't be a problem... the config is free to be updated
arbitrarily (within a reasonable bound). I fixed a few problems, and here's
what I'm seeing at the end for SNS-1:

{
  "version": "1",
  "localnet": {
    "subsystem": {
      "bacnet": {
        "local_id": "4138091"
      }
    }
  },
  "pointset": {
    "points": {
      "room_temp": {
        "ref": "AI3.Present_Value"
      },
      "humidity": {
        "ref": "AI6.Present_Value"
      },
      "sound_volume": {
        "ref": "AV30.Present_Value"
      },
      "sound_level": {
        "ref": "AI17.Present_Value"
      },
      "temperature_setpoint": {
        "ref": "AV33.Present_Value"
      }
    }
  },
  "system": {
    "min_loglevel": 400
  },
  "timestamp": "2021-09-29T02:15:12.840Z"
}

... which nearly matches the generated config:

{
  "timestamp" : "2021-09-12T20:39:43Z",
  "localnet" : {
    "subsystem" : {
      "bacnet" : {
        "local_id" : "4138091"
      }
    }
  },
  "pointset" : {
    "points" : {
      "humidity" : {
        "ref" : "AI6.Present_Value"
      },
      "room_temp" : {
        "ref" : "AI3.Present_Value"
      },
      "sound_level" : {
        "ref" : "AI17.Present_Value"
      },
      "sound_volume" : {
        "ref" : "AV30.Present_Value"
      },
      "temperature_setpoint" : {
        "ref" : "AV33.Present_Value"
      }
    }
  }
}

**Comment by noursaidi** [comment]
This has addressed the end of test configuration issue I was having
